name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/build-ios.yml'
      - 'cpp/**'
      - 'ios/**'
      - '*.podspec'
      - 'example/ios/**'
      - 'argon2/**'

jobs:
  build:
    name: Build iOS Example App
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node_modules
        run: npm install
      - name: Install node_modules for example/
        run: npm --prefix ./example install

      - name: Restore buildcache
        uses: mikehardy/buildcache-action@v1
        continue-on-error: true

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: true
          working-directory: example/ios

      - name: Restore Pods cache
        uses: actions/cache@v3
        with:
          path: |
            example/ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install Pods
        run: cd example/ios; bundle exec pod check || bundle exec pod install
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Build App
        run: "set -o pipefail && xcodebuild \
          CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ \
          -derivedDataPath build -UseModernBuildSystem=YES \
          -workspace MmkvExample.xcworkspace \
          -scheme MmkvExample \
          -sdk iphonesimulator \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 11 Pro' \
          build \
          CODE_SIGNING_ALLOWED=NO | xcpretty"
